### ISSUE TITLE
Why not scrape the API instead of HTML?

### ISSUE THREAD

**Issue by adsr** [clarencechaan/ufc-cal#1]
Hello, I'm curious why you decided to scrape HTML instead of their JSON API, e.g., https://d29dxerjsp82wz.cloudfront.net/api/v3/event/live/1171.json. The event ids seem to be (mostly) sequential. I'd think that'd be easier and less brittle than parsing markup. Thanks for making this calendar in any case!

**Comment by moquette** [comment]
Excellent observation. Nonetheless, I too wish to thank you. Certainly one of the better UFC calendar.

**Comment by clarencechaan** [comment]
I had no clue this existed. Didn’t think to check the dev tools to find the API url right from the UFC site so thanks for the heads up, this should be a huge help. 


One downgrade and one sidegrade from switching over seems to be 1) accented letters in fighter names are stripped to non-accented letters (e.g. Jiří Procházka -> Jiri Prochazka) and 2) fighter ranks aren’t provided by the API (less info displayed, but also less clutter), but I think the changes are worth the added robustness. 


I’ll just have to figure out a way to keep track of what event ID we’re currently at and which event IDs to check so I’m not absolutely hammering their API. 


Edit: After working on most of the implementation there looks to be a few more drawbacks than anticipated. The API doesn't seem to provide a URL of the UFC event page. As a workaround I put a Google search query of the event title in the description instead but it's not ideal. Also, the API event start times correspond to the prelims/early prelims times. There does exist a property for the main card start times, but they're missing for at least one of the (upcoming) events, and estimating main card start times isn't something I'm willing to compromise on, since date/time accuracy is probably the most important thing. Unless I'm missing something someone can point out to me, I'll have to close this due to the API missing a bit more information than I'd like when compared to the website.

**Comment by moquette** [comment]
Learning a lot from your creativity!
Just out of curiosity, is there a chance you could add the prelims/early prelim times as well?

**Comment by clarencechaan** [comment]
> Just out of curiosity, is there a chance you could add the prelims/early prelim times as well?

Done. Note that the times are relative to the main card start time, e.g., "3 hrs before Main" rather than being a direct time; I don't think it's possible to localize the times to each user's timezone in the description part of a calendar entry, so this will have to do.
